<section id="login">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-wrap">
                <h1>Bem vindo a nossa empresa!</h1>
                <div>Texto sobre a nossa empresa!</div>    
                </div>
            </div> <!-- /.col-xs-12 -->            
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</section>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>Page © - 2014</p>
                <p>Powered by <strong><a href="http://www.facebook.com/tavo.qiqe.lucero" target="_blank">TavoQiqe</a></strong></p>
            </div>
        </div>
    </div>
</footer>