<section id="login">
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-wrap">
                <h1>Cadastre-se</h1>
                    <form role="form" action="<?php echo $this->baseUrl.$this->action; ?>" method="post" id="login-form" autocomplete="off">
                        <input type="hidden" name="logar">
                        <div class="form-group">
                            <label for="nome" class="sr-only">Nome</label>
                            <input type="text" name="nome" id="nome" class="form-control" placeholder="Nome">
                        </div>
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="email" name="user" id="email" class="form-control" placeholder="somebody@example.com">
                        </div>
                        <div class="form-group">
                            <label for="data" class="sr-only">Data de Nascimento</label>
                            <input type="datetime" name="data" id="data" class="form-control" placeholder="99/99/9999">
                        </div>
                            <div class="form-group">
                            <label for="sexo" class="sr-only">Sexo</label>
                            <input type="radio" name="sexo" id="sexo" class="">Masculino<br>
                            <input type="radio" name="sexo" id="sexo" class="">Feminino
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Senha</label>
                            <input type="password" name="senha" id="key" class="form-control" placeholder="Senha">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Confirmar Senha</label>
                            <input type="password" name="senha" id="key" class="form-control" placeholder="Confirmar Senha">
                        </div>                        
                        <div class="checkbox">
                            <span class="character-checkbox" onclick="showPassword()"></span>
                            <span class="label">Li e aceito os termos</span>
                        </div>
                        <input type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block" value="Cadastrar">
                    </form>
                    <hr>
                </div>
            </div> <!-- /.col-xs-12 -->
            <div class="col-xs-6">
                <div class="form-wrap">
                <h1>Faça o seu Login</h1>
                    <form role="form" action="<?php echo $this->baseUrl.$this->action; ?>" method="post" id="login-form" autocomplete="off">
                        <input type="hidden" name="logar">
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="email" name="user" id="email" class="form-control" placeholder="somebody@example.com">
                        </div>
                        <div class="form-group">
                            <label for="key" class="sr-only">Password</label>
                            <input type="password" name="senha" id="key" class="form-control" placeholder="Password">
                        </div>
                        <div class="checkbox">
                            <span class="character-checkbox" onclick="showPassword()"></span>
                            <span class="label">Mostrar Senha</span>
                        </div>
                        <input type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block" value="Logar">
                    </form>
                    <a href="javascript:;" class="forget" data-toggle="modal" data-target=".forget-modal">Forgot your password?</a>
                    <hr>
                </div>
            </div> <!-- /.col-xs-12 -->            
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</section>

<div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Recovery password</h4>
            </div>
            <div class="modal-body">
                <p>Type your email account</p>
                <input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-custom">Recovery</button>
            </div>
        </div> <!-- /.modal-content -->
    </div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->
<?php echo $valor; ?>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>Page © - 2014</p>
                <p>Powered by <strong><a href="http://www.facebook.com/tavo.qiqe.lucero" target="_blank">TavoQiqe</a></strong></p>
            </div>
        </div>
    </div>
</footer>